version: '3.8'

services:
  db:
    image: postgres:15
    container_name: chopped_db
    restart: always
    environment:
      POSTGRES_USER: thiagoserebrinsky
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thiagoserebrinsky -d chopped"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
